//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace GDFramework.LubanKit.Cfg.worldObj
{
    public partial class TbObj
    {
        private readonly System.Collections.Generic.Dictionary<int, worldObj.WorldObj> _dataMap;
        private readonly System.Collections.Generic.List<worldObj.WorldObj> _dataList;

        public TbObj(JSONNode _buf)
        {
            _dataMap = new System.Collections.Generic.Dictionary<int, worldObj.WorldObj>();
            _dataList = new System.Collections.Generic.List<worldObj.WorldObj>();

            foreach (JSONNode _ele in _buf.Children)
            {
                worldObj.WorldObj _v;
                {
                    if (!_ele.IsObject)
                    {
                        throw new SerializationException();
                    }

                    _v = worldObj.WorldObj.DeserializeWorldObj(_ele);
                }
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }
        }

        public System.Collections.Generic.Dictionary<int, worldObj.WorldObj> DataMap => _dataMap;
        public System.Collections.Generic.List<worldObj.WorldObj> DataList => _dataList;

        public worldObj.WorldObj GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
        public worldObj.WorldObj Get(int key) => _dataMap[key];
        public worldObj.WorldObj this[int key] => _dataMap[key];

        public void ResolveRef(LubanTablesData tables)
        {
            foreach (var _v in _dataList)
            {
                _v.ResolveRef(tables);
            }
        }
    }
}