
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace GDFramework.LubanKit.Cfg.worldObj
{
public sealed partial class WorldObj : Luban.BeanBase
{
    public WorldObj(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["desc"].IsString) { throw new SerializationException(); }  Desc = _buf["desc"]; }
        { if(!_buf["initialHealthy"].IsNumber) { throw new SerializationException(); }  InitialHealthy = _buf["initialHealthy"]; }
        { if(!_buf["maxHealthy"].IsNumber) { throw new SerializationException(); }  MaxHealthy = _buf["maxHealthy"]; }
        { if(!_buf["initialArmor"].IsNumber) { throw new SerializationException(); }  InitialArmor = _buf["initialArmor"]; }
        { if(!_buf["maxArmor"].IsNumber) { throw new SerializationException(); }  MaxArmor = _buf["maxArmor"]; }
        { if(!_buf["initialMana"].IsNumber) { throw new SerializationException(); }  InitialMana = _buf["initialMana"]; }
        { if(!_buf["maxMana"].IsNumber) { throw new SerializationException(); }  MaxMana = _buf["maxMana"]; }
    }

    public static WorldObj DeserializeWorldObj(JSONNode _buf)
    {
        return new worldObj.WorldObj(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名字
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 初始生命值
    /// </summary>
    public readonly int InitialHealthy;
    /// <summary>
    /// 最大生命值
    /// </summary>
    public readonly float MaxHealthy;
    /// <summary>
    /// 初始护甲值
    /// </summary>
    public readonly float InitialArmor;
    /// <summary>
    /// 最大护甲值
    /// </summary>
    public readonly float MaxArmor;
    /// <summary>
    /// 初始魔法值
    /// </summary>
    public readonly float InitialMana;
    /// <summary>
    /// 最大魔法值
    /// </summary>
    public readonly float MaxMana;
   
    public const int __ID__ = -171930642;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(LubanTablesData tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "initialHealthy:" + InitialHealthy + ","
        + "maxHealthy:" + MaxHealthy + ","
        + "initialArmor:" + InitialArmor + ","
        + "maxArmor:" + MaxArmor + ","
        + "initialMana:" + InitialMana + ","
        + "maxMana:" + MaxMana + ","
        + "}";
    }
}

}

