#if UNITY_EDITOR
using System;
using System.IO;
using System.Text;
using System.Linq;
using System.Collections.Generic;
using GDFrameworkExtend.LogKit;
using UnityEditor;
using UnityEngine;

namespace YooAsset.Editor
{
    public class AssetCodeGenerator
    {
        // ID分配规则：基于Group名称分配ID范围
        private static readonly Dictionary<string, int> GroupIDRanges = new Dictionary<string, int>
        {
            {"Sprite",0},
            { "Music", 10000000 },
            { "Prefabs", 20000000 }
        };

        [MenuItem("YooAsset/Generate Asset Code")]
        public static void GenerateAssetCode()
        {
            StringBuilder codeBuilder = new StringBuilder();
            StringBuilder idMappingBuilder = new StringBuilder();

            // Add file header
            codeBuilder.AppendLine("// This file is auto-generated by YooAsset AssetCodeGenerator");
            codeBuilder.AppendLine("// Do not modify this file - your changes will be lost");
            codeBuilder.AppendLine();

            // Add namespace
            codeBuilder.AppendLine("namespace GDFramework.FrameData");
            codeBuilder.AppendLine("{");

            // ID映射类头部
            idMappingBuilder.AppendLine("// This file is auto-generated by YooAsset AssetCodeGenerator");
            idMappingBuilder.AppendLine("// Asset ID Mapping - Do not modify this file");
            idMappingBuilder.AppendLine();
            idMappingBuilder.AppendLine("using System.Collections.Generic;");
            idMappingBuilder.AppendLine();
            idMappingBuilder.AppendLine("namespace GDFramework.FrameData");
            idMappingBuilder.AppendLine("{");
            idMappingBuilder.AppendLine("    public static class AssetIDMapping");
            idMappingBuilder.AppendLine("    {");

            // 存储所有资源的ID映射 - 按Group分组
            Dictionary<string, List<AssetInfo>> groupAssets = new Dictionary<string, List<AssetInfo>>();

            // Process each package
            foreach (var package in AssetBundleCollectorSettingData.Setting.Packages)
            {
                ProcessPackageForMapping(package, codeBuilder, groupAssets);
            }

            // 生成ID映射
            GenerateIDMapping(groupAssets, idMappingBuilder);

            codeBuilder.AppendLine("}");
            idMappingBuilder.AppendLine("    }");
            idMappingBuilder.AppendLine("}");

            // Write to files
            SaveToFile(codeBuilder.ToString(), "AssetPathConstants.cs");
            SaveToFile(idMappingBuilder.ToString(), "AssetIDMapping.cs");

            LogKit.Log("YooAsset code generation completed!");
            AssetDatabase.Refresh();
        }

        private static void ProcessPackageForMapping(AssetBundleCollectorPackage package, StringBuilder codeBuilder,
            Dictionary<string, List<AssetInfo>> groupAssets)
        {
            codeBuilder.AppendLine();
            codeBuilder.AppendLine($"   public struct {SanitizeIdentifier(package.PackageName)}");
            codeBuilder.AppendLine("    {");

            // Process each group within the package
            foreach (var group in package.Groups)
            {
                var assets = ProcessGroup(group, codeBuilder, package.PackageName);

                // 按Group名称收集资源
                if (assets.Count > 0)
                {
                    if (!groupAssets.ContainsKey(group.GroupName))
                        groupAssets[group.GroupName] = new List<AssetInfo>();

                    groupAssets[group.GroupName].AddRange(assets);
                }
            }

            codeBuilder.AppendLine("    }");
        }

        private static List<AssetInfo> ProcessGroup(AssetBundleCollectorGroup group, StringBuilder codeBuilder,
            string packageName)
        {
            List<AssetInfo> groupAssets = new List<AssetInfo>();

            if (!IsGroupActive(group))
                return groupAssets;

            codeBuilder.AppendLine();
            codeBuilder.AppendLine($"       public struct {SanitizeIdentifier(group.GroupName)}");
            codeBuilder.AppendLine("       {");

            // Process collectors within the group
            foreach (var collector in group.Collectors)
            {
                if (string.IsNullOrEmpty(collector.CollectPath))
                    continue;

                var collectorAssets = ProcessCollector(collector, codeBuilder, packageName, group.GroupName);
                groupAssets.AddRange(collectorAssets);
            }

            codeBuilder.AppendLine("       }");
            return groupAssets;
        }

        private static List<AssetInfo> ProcessCollector(AssetBundleCollector collector, StringBuilder codeBuilder,
            string packageName, string groupName)
        {
            List<AssetInfo> collectorAssets = new List<AssetInfo>();

            try
            {
                if (collector.CollectorType == ECollectorType.MainAssetCollector ||
                    collector.CollectorType == ECollectorType.StaticAssetCollector)
                {
                    string collectPath = collector.CollectPath;
                    bool isFolder = AssetDatabase.IsValidFolder(collectPath);

                    // 1) 根据采集路径计算 bundle 名 & struct 名
                    string bundleName = GenerateBundleName(packageName, collectPath);
                    string structName = GenerateCollectorStructName(collectPath); // 新增：同一文件夹 => 同一 struct

                    // 2) 收集该 Collector 下的所有有效地址
                    HashSet<string> addresses = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
                    if (isFolder)
                    {
                        string[] assetGuids = AssetDatabase.FindAssets("t:Object", new[] { collectPath });
                        foreach (string guid in assetGuids)
                        {
                            string assetPath = AssetDatabase.GUIDToAssetPath(guid);
                            if (ShouldSkipAsset(assetPath))
                                continue;
                            addresses.Add(Path.GetFileNameWithoutExtension(assetPath));
                        }
                    }
                    else
                    {
                        // 单文件采集器
                        addresses.Add(Path.GetFileNameWithoutExtension(collectPath));
                    }

                    // 3) 生成“同一 struct，多字段”
                    codeBuilder.AppendLine();
                    codeBuilder.AppendLine($"           public struct {structName}");
                    codeBuilder.AppendLine("           {");
                    codeBuilder.AppendLine($"               public const string BundleName = \"{bundleName}\";");

                    // 稳定排序，避免生成顺序抖动
                    var ordered = addresses.OrderBy(a => a, StringComparer.OrdinalIgnoreCase).ToList();

                    // 防重名（极少见：同一文件夹里不同资源算出同名字段）
                    HashSet<string> usedFieldNames = new HashSet<string>(StringComparer.Ordinal);

                    foreach (var address in ordered)
                    {
                        string fieldName = EnsureUnique(SanitizeIdentifier(address), usedFieldNames); // 字段名
                        string assetAddress = $"yoo:{address}";

                        codeBuilder.AppendLine($"               public const string {fieldName} = \"{assetAddress}\";");

                        collectorAssets.Add(new AssetInfo
                        {
                            PackageName = packageName,
                            GroupName = groupName,
                            AssetName = address,
                            ClassName = structName, // 记录所在 struct（可用于后续扩展）
                            AssetAddress = assetAddress,
                            BundleName = bundleName
                        });
                    }

                    codeBuilder.AppendLine("           }");
                }
            }
            catch (Exception ex)
            {
                LogKit.Error($"Error processing collector {collector.CollectPath}: {ex.Message}");
            }

            return collectorAssets;
        }

        // 根据采集路径生成“同一 Collector 的结构体名”
        // 文件夹 => 用文件夹名；单文件 => 用文件名；尾缀用 AssetGroup 与之前的单资源 struct 区分
        private static string GenerateCollectorStructName(string collectPath)
        {
            string name = AssetDatabase.IsValidFolder(collectPath)
                ? Path.GetFileName(collectPath.TrimEnd('/'))
                : Path.GetFileNameWithoutExtension(collectPath);

            // 规范化并追加后缀
            return SanitizeIdentifier(name) + "AssetGroup";
        }

        // 确保字段名不重复（极端情况下做 a, a_1, a_2…）
        private static string EnsureUnique(string baseName, HashSet<string> used)
        {
            string name = baseName;
            int i = 1;
            while (used.Contains(name))
                name = $"{baseName}_{i++}";
            used.Add(name);
            return name;
        }

        private static void GenerateIDMapping(Dictionary<string, List<AssetInfo>> groupAssets,
            StringBuilder idMappingBuilder)
        {
            // 生成各个Group的ID常量类
            foreach (var group in groupAssets)
            {
                string groupName = group.Key;
                var assets = group.Value;

                // 只为指定的Group生成ID
                if (!GroupIDRanges.ContainsKey(groupName))
                    continue;

                idMappingBuilder.AppendLine();
                idMappingBuilder.AppendLine($"        public struct {groupName}IDs");
                idMappingBuilder.AppendLine("        {");

                int baseID = GroupIDRanges[groupName];
                int currentID = baseID;

                foreach (var asset in assets)
                {
                    string idConstantName = SanitizeIdentifier(asset.AssetName).ToUpper();
                    idMappingBuilder.AppendLine($"            public const int {idConstantName} = {currentID};");
                    currentID++;
                }

                idMappingBuilder.AppendLine("        }");
            }

            // 生成ID到资源地址的映射字典
            idMappingBuilder.AppendLine();
            idMappingBuilder.AppendLine("        // ID到资源地址的映射");
            idMappingBuilder.AppendLine(
                "        public static readonly Dictionary<int, string> IDToAssetPath = new Dictionary<int, string>");
            idMappingBuilder.AppendLine("        {");

            foreach (var group in groupAssets)
            {
                string groupName = group.Key;
                var assets = group.Value;

                if (!GroupIDRanges.ContainsKey(groupName))
                    continue;

                int baseID = GroupIDRanges[groupName];
                int currentID = baseID;

                foreach (var asset in assets)
                {
                    idMappingBuilder.AppendLine($"            {{{currentID}, \"{asset.AssetAddress}\"}},");
                    currentID++;
                }
            }

            idMappingBuilder.AppendLine("        };");

            // 生成资源地址到ID的映射字典
            idMappingBuilder.AppendLine();
            idMappingBuilder.AppendLine("        // 资源地址到ID的映射");
            idMappingBuilder.AppendLine(
                "        public static readonly Dictionary<string, int> AssetPathToID = new Dictionary<string, int>");
            idMappingBuilder.AppendLine("        {");

            foreach (var group in groupAssets)
            {
                string groupName = group.Key;
                var assets = group.Value;

                if (!GroupIDRanges.ContainsKey(groupName))
                    continue;

                int baseID = GroupIDRanges[groupName];
                int currentID = baseID;

                foreach (var asset in assets)
                {
                    idMappingBuilder.AppendLine($"            {{\"{asset.AssetAddress}\", {currentID}}},");
                    currentID++;
                }
            }

            idMappingBuilder.AppendLine("        };");

            // 添加辅助方法
            idMappingBuilder.AppendLine();
            idMappingBuilder.AppendLine("        /// <summary>");
            idMappingBuilder.AppendLine("        /// 根据ID获取资源地址");
            idMappingBuilder.AppendLine("        /// </summary>");
            idMappingBuilder.AppendLine("        public static string GetAssetPath(int id)");
            idMappingBuilder.AppendLine("        {");
            idMappingBuilder.AppendLine(
                "            return IDToAssetPath.TryGetValue(id, out string path) ? path : null;");
            idMappingBuilder.AppendLine("        }");

            idMappingBuilder.AppendLine();
            idMappingBuilder.AppendLine("        /// <summary>");
            idMappingBuilder.AppendLine("        /// 根据资源地址获取ID");
            idMappingBuilder.AppendLine("        /// </summary>");
            idMappingBuilder.AppendLine("        public static int GetAssetID(string assetPath)");
            idMappingBuilder.AppendLine("        {");
            idMappingBuilder.AppendLine(
                "            return AssetPathToID.TryGetValue(assetPath, out int id) ? id : -1;");
            idMappingBuilder.AppendLine("        }");
        }

        // 资源信息结构
        private class AssetInfo
        {
            public string PackageName;
            public string GroupName;
            public string AssetName;
            public string ClassName;
            public string AssetAddress;
            public string BundleName;
        }

        private static bool ShouldSkipAsset(string assetPath)
        {
            return AssetDatabase.IsValidFolder(assetPath) ||
                   assetPath.EndsWith(".cs") ||
                   assetPath.EndsWith(".js") ||
                   assetPath.EndsWith(".dll");
        }

        // 生成与构建结果一致的BundleName
        private static string GenerateBundleName(string packageName, string collectPath)
        {
            // 统一转换为小写
            packageName = packageName.ToLower();

            // 处理路径规则（与YooAsset构建逻辑匹配）
            string normalizedPath = collectPath
                .Replace("Assets/", "") // 移除Assets前缀
                .ToLower() // 全小写
                .Replace('/', '_') // 替换路径分隔符
                .Replace(' ', '_'); // 替换空格

            // 如果是文件，取所在目录
            if (!AssetDatabase.IsValidFolder(collectPath))
            {
                string dirPath = Path.GetDirectoryName(normalizedPath);
                if (!string.IsNullOrEmpty(dirPath))
                    normalizedPath = dirPath;
            }

            // 合并包名与路径
            return $"{packageName}_{normalizedPath}";
        }

        // 新增：根据资源名称生成Asset类名
        private static string GenerateAssetClassName(string assetName)
        {
            if (string.IsNullOrEmpty(assetName))
                return "DefaultAsset";

            // 首字母大写
            string className = char.ToUpper(assetName[0]) + assetName.Substring(1);

            // 清理无效字符
            StringBuilder sb = new StringBuilder();
            foreach (char c in className)
            {
                if (char.IsLetterOrDigit(c))
                    sb.Append(c);
                else
                    sb.Append('_');
            }

            string result = sb.ToString();

            // 确保不以数字开头
            if (char.IsDigit(result[0]))
                result = "_" + result;

            // 添加Asset后缀
            return result + "Asset";
        }

        private static bool IsGroupActive(AssetBundleCollectorGroup group)
        {
            IActiveRule activeRule = AssetBundleCollectorSettingData.GetActiveRuleInstance(group.ActiveRuleName);
            return activeRule.IsActiveGroup(new GroupData(group.GroupName));
        }

        private static string SanitizeIdentifier(string input)
        {
            if (string.IsNullOrEmpty(input))
                return "Default";

            // 保留字母数字，其他字符转下划线
            StringBuilder sb = new StringBuilder();
            foreach (char c in input)
            {
                if (char.IsLetterOrDigit(c))
                    sb.Append(c);
                else
                    sb.Append('_');
            }

            string result = sb.ToString();
            if (char.IsDigit(result[0]))
                result = "_" + result;

            return result;
        }

        private static void SaveToFile(string content, string fileName)
        {
            string directoryPath = "Assets/GDFramework/GDFrameworkData";
            if (!Directory.Exists(directoryPath))
                Directory.CreateDirectory(directoryPath);

            string filePath = Path.Combine(directoryPath, fileName);
            File.WriteAllText(filePath, content, Encoding.UTF8);
            LogKit.Log($"File saved to {filePath}");
        }
    }
}
#endif