// This file is auto-generated by YooAsset AssetCodeGenerator
// Do not modify this file - your changes will be lost

namespace GDFramework.FrameData
{

   public class DefaultPackage
    {

       public class Config
       {

           public class WorldPersistentAsset
           {
               public const string BundleName = "defaultpackage_game_res_configs_worlddata_worldpersistent.json";
               public const string WorldPersistent = "yoo:WorldPersistent";
           }
       }

       public class GameModelData
       {

           public class GameInputAsset
           {
               public const string BundleName = "defaultpackage_gdframework_res_input_gameinput.inputactions";
               public const string GameInput = "yoo:GameInput";
           }

           public class TbmultilingualAsset
           {
               public const string BundleName = "defaultpackage_gdframework_res_mul_tbmultilingual.json";
               public const string tbmultilingual = "yoo:tbmultilingual";
           }
       }

       public class UGUI
       {

           public class UI_TestPanelAsset
           {
               public const string BundleName = "defaultpackage_gdframework_res_uiprefabs_ui_testpanel.prefab";
               public const string UI_TestPanel = "yoo:UI_TestPanel";
           }
       }
    }
}
