// This file is auto-generated by YooAsset AssetCodeGenerator
// Asset ID Mapping - Do not modify this file

using System.Collections.Generic;

namespace GDFramework.FrameData
{
    public static class AssetIDMapping
    {

        public struct PrefabsIDs
        {
            public const int PLAYER = 2000;
        }

        // ID到资源地址的映射
        public static readonly Dictionary<int, string> IDToAssetPath = new Dictionary<int, string>
        {
            {2000, "yoo:Player"},
        };

        // 资源地址到ID的映射
        public static readonly Dictionary<string, int> AssetPathToID = new Dictionary<string, int>
        {
            {"yoo:Player", 2000},
        };

        /// <summary>
        /// 根据ID获取资源地址
        /// </summary>
        public static string GetAssetPath(int id)
        {
            return IDToAssetPath.TryGetValue(id, out string path) ? path : null;
        }

        /// <summary>
        /// 根据资源地址获取ID
        /// </summary>
        public static int GetAssetID(string assetPath)
        {
            return AssetPathToID.TryGetValue(assetPath, out int id) ? id : -1;
        }
    }
}
