// This file is auto-generated by YooAsset AssetCodeGenerator
// Asset ID Mapping - Do not modify this file

using System.Collections.Generic;

namespace GDFramework.FrameData
{
    public static class AssetIDMapping
    {

        public struct MusicIDs
        {
            public const int DUNGEON_01 = 10000000;
            public const int DUNGEON_02 = 10000001;
        }

        public struct PrefabsIDs
        {
            public const int UNIVERSECONTROLLER = 20000000;
        }

        // ID到资源地址的映射
        public static readonly Dictionary<int, string> IDToAssetPath = new Dictionary<int, string>
        {
            {10000000, "yoo:Dungeon_01"},
            {10000001, "yoo:Dungeon_02"},
            {20000000, "yoo:UniverseController"},
        };

        // 资源地址到ID的映射
        public static readonly Dictionary<string, int> AssetPathToID = new Dictionary<string, int>
        {
            {"yoo:Dungeon_01", 10000000},
            {"yoo:Dungeon_02", 10000001},
            {"yoo:UniverseController", 20000000},
        };

        /// <summary>
        /// 根据ID获取资源地址
        /// </summary>
        public static string GetAssetPath(int id)
        {
            return IDToAssetPath.TryGetValue(id, out string path) ? path : null;
        }

        /// <summary>
        /// 根据资源地址获取ID
        /// </summary>
        public static int GetAssetID(string assetPath)
        {
            return AssetPathToID.TryGetValue(assetPath, out int id) ? id : -1;
        }
    }
}
