// This file is auto-generated by YooAsset AssetCodeGenerator
// Do not modify this file - your changes will be lost

namespace GDFramework.FrameData
{

   public struct DefaultPackage
    {

       public struct GameConfig
       {

           public struct WorldDataAssetGroup
           {
               public const string BundleName = "defaultpackage_game_res_configs_worlddata";
               public const string areaBlock_01areaBlock_01 = "yoo:areaBlock_01areaBlock_01";
               public const string areaBlock_02areaBlock_02 = "yoo:areaBlock_02areaBlock_02";
               public const string earthearth = "yoo:earthearth";
               public const string node_01node_01 = "yoo:node_01node_01";
               public const string room_01room_01 = "yoo:room_01room_01";
           }
       }

       public struct GameModelData
       {

           public struct GameInputAssetGroup
           {
               public const string BundleName = "defaultpackage_gdframework_res_input_gameinput.inputactions";
               public const string GameInput = "yoo:GameInput";
           }

           public struct TbmultilingualAssetGroup
           {
               public const string BundleName = "defaultpackage_gdframework_res_mul_tbmultilingual.json";
               public const string Tbmultilingual = "yoo:Tbmultilingual";
           }
       }

       public struct UI
       {

           public struct UI_NodeAssetGroup
           {
               public const string BundleName = "defaultpackage_game_res_prefabs_ui_node.prefab";
               public const string UI_Node = "yoo:UI_Node";
           }
       }

       public struct Music
       {

           public struct Dungeon_01AssetGroup
           {
               public const string BundleName = "defaultpackage_game_res_musics_bgm_dungeon_01.mp3";
               public const string Dungeon_01 = "yoo:Dungeon_01";
           }

           public struct Dungeon_02AssetGroup
           {
               public const string BundleName = "defaultpackage_game_res_musics_bgm_dungeon_02.mp3";
               public const string Dungeon_02 = "yoo:Dungeon_02";
           }
       }

       public struct Particle
       {
       }

       public struct Prefabs
       {

           public struct PlayerAssetGroup
           {
               public const string BundleName = "defaultpackage_game_res_prefabs_player.prefab";
               public const string Player = "yoo:Player";
           }
       }
    }
}
