// This file is auto-generated by YooAsset AssetCodeGenerator
// Do not modify this file - your changes will be lost

namespace GDFramework.FrameData
{

   public class DefaultPackage
    {

       public class Config
       {
       }

       public class GameModelData
       {

           public class defaultpackage_gdframework_gdframeworkdata_gameinput_inputactions
           {
               public const string BundleName = "defaultpackage_gdframework_gdframeworkdata_gameinput.inputactions";
               public const string GameInput = "yoo:GameInput";
           }

           public class defaultpackage_gdframework_res_mul_tbmultilingual_json
           {
               public const string BundleName = "defaultpackage_gdframework_res_mul_tbmultilingual.json";
               public const string tbmultilingual = "yoo:tbmultilingual";
           }
       }

       public class UGUI
       {
           public class defaultpackage_gdframework_res_uiprefabs_ui_testpanel_prefab
           {
               public const string BundleName = "defaultpackage_gdframework_res_uiprefabs_ui_testpanel.prefab";
               public const string UI_TestPanel = "yoo:UI_TestPanel";
           }
       }
    }
}
