//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDAssetBundle
{
    
    public class English
    {
        public const string BundleName = "english";
    }
    public class Gameinput_inputactions
    {
        public const string BundleName = "gameinput_inputactions";
        public const string GameInput = "GameInput";
    }
    public class Simplifiedchinese
    {
        public const string BundleName = "simplifiedchinese";
    }
    public class Tbmultilingual_json
    {
        public const string BundleName = "tbmultilingual_json";
        public const string tbmultilingual = "tbmultilingual";
    }
}
