// This file is auto-generated by YooAsset Code Generator
// Do not modify this file manually

using System;
using YooAsset;

namespace GDFramworkData
{
    public static class OtherAssets
    {
        /// <summary>
        /// Assets/GDFramework/Res/Mul/tbmultilingual.json
        /// </summary>
        public const string Tbmultilingual = "Assets/GDFramework/Res/Mul/tbmultilingual.json";
        /// <summary>
        /// Assets/GDFramework/GDFrameworkData/GameInput.inputactions
        /// </summary>
        public const string GameInput = "Assets/GDFramework/GDFrameworkData/GameInput.inputactions";

    }
}
