// This file is auto-generated by YooAsset AssetCodeGenerator
// Do not modify this file - your changes will be lost

namespace YooAsset
{
    /// <summary>
    /// Asset path constants for use with YooAsset
    /// </summary>
    public static class Assets
    {

        /// <summary>
        /// Assets in package: DefaultPackage
        /// </summary>
        public static class DefaultPackage
        {

            /// <summary>
            /// Assets in group: Config
            /// 配置
            /// </summary>
            public static class Config
            {
            }

            /// <summary>
            /// Assets in group: GameModelData
            /// 游戏默认配置
            /// </summary>
            public static class GameModelData
            {
                /// <summary>Asset: Assets/GDFramework/GDFrameworkData/GameInput.inputactions</summary>
                public const string GameInput = "Assets/GDFramework/GDFrameworkData/GameInput.inputactions";

                /// <summary>Asset: Assets/GDFramework/Res/Mul/tbmultilingual.json</summary>
                public const string tbmultilingual = "Assets/GDFramework/Res/Mul/tbmultilingual.json";

            }

            /// <summary>
            /// Assets in group: UGUI
            /// UI面板
            /// </summary>
            public static class UGUI
            {
                /// <summary>Asset: Assets/GDFramework/Res/UIPrefabs/UI_TestPanel.prefab</summary>
                public const string UI_TestPanel = "Assets/GDFramework/Res/UIPrefabs/UI_TestPanel.prefab";

            }
        }
    }
}
