
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace GDFramework.LubanKit.Cfg
{
public partial class LubanTablesData
{
    public item.TbItem TbItem {get; }
    public worldObj.TbObj TbObj {get; }

    public LubanTablesData(System.Func<string, JSONNode> loader)
    {
        TbItem = new item.TbItem(loader("item_tbitem"));
        TbObj = new worldObj.TbObj(loader("worldobj_tbobj"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbItem.ResolveRef(this);
        TbObj.ResolveRef(this);
    }
}

}
